{
    "name": "Salon Website Templates",
    "version": "18.0.1.0.0",
    "summary": "Salon Website Templates",
    "category": "Webiste",
    "author": "ForeFront Technologies",
    "depends": ['base','web','website'],
    "data": [
        "views/main_page.xml",
        "views/about_page.xml",
        "views/service_page.xml",
        "views/price_page.xml",
        "views/contact_page.xml",
        "views/team_page.xml",
        "views/testimonial_page.xml",
        "views/gallery_page.xml",
        "views/signup_page.xml",
        "views/signup_confirmation_page.xml",
        "views/appointment_page.xml",
        "views/contact_confirmation_page.xml",
        "views/booking_confirm_page.xml",
    ],
    "license": "LGPL-3",
    "installable": True,
    "application": True,
}
